[pytest]
testpaths = tests
addopts = --alluredir=allure-results
markers =
    q1: test scenario 1 - locked_out_user login
    q2: test scenario 2 - standard_user full purchase
    q3: test scenario 3 - performance_glitch_user full purchase